### ISSUE TITLE
M1.3 UX design for Debrief Lite

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#2956]
Once we've scoped the requirement for Debrief-Lite (#2925) we should invite a UX design for the app.

I'm consciously breaking this down into phases.
* [ ] Sprint 1. Overall approach. Mouse mode buttons
* [ ] Sprint 2. Time controller. Shape palette. Outline (layer) view.
* [ ] Sprint 3. Narrative Viewer
* [ ] Sprint 4. Export to PPT.

Here is the User Story Map:
![d-lite user story mapping](https://user-images.githubusercontent.com/1108513/42322815-c912cf44-8055-11e8-97cd-3b2ea36aab05.png)

Here are the customer thoughts on the UI:
![customer thoughts on ui](https://user-images.githubusercontent.com/1108513/42324911-856f2a56-805c-11e8-9529-ebfddcbfcfb6.png)

Here is the phased implementation plan:
![debrief lite delivery plan](https://user-images.githubusercontent.com/1108513/42940829-b414434a-8b52-11e8-8dbd-3ae81a0b248b.png)

We've got working software (*Debrief Classic*) that _should_ be able to act as base for Debrief-Lite (screenshot below). 

But, instead of basing Lite on that app, it would be good to have a fresh UI design - then either transform Debrief Classic into Debrief-Lite, or produce Debrief Lite from scratch, depending on the gap analysis.

So, I'm expecting to do some User Story Mapping, then hand these to UX, to design an overall UI.

We can expect this UX design to include:
* overall screen layout
* design for discrete elements:
    * time controller
    * narrative (diary) window
    * time-variable graph window
    * Outline/tree view to switch data on/off
* support for performing operations:
    * filter data to set time period
    * export data to PPT/Word (animated or still)

![debrieflite](https://user-images.githubusercontent.com/1108513/42147621-9ab8bf78-7dc6-11e8-90a2-0777c76e316f.png)

**Comment by IanMayo** [comment]
UX development now up & running
