### ISSUE TITLE
M7.2 Expose object model

### ISSUE THREAD

**Issue by Waynearendse** [debrief/debrief#3404]
As a **data scientist** I would like an exposed object model so I can manipulate those objects

## Acceptance criteria :
* [ ] object model visible in the module explorer
* [ ] we can drag object into the javascript editor
* [ ] code completion in the scripting shell for a debrief object 

## Assumption:
That as soon as we make the object model visible in the module explorer we should be able to drag the object into the javascript editor.

**Comment by IanMayo** [comment]
Object model now exposed.
