### ISSUE TITLE
Heuristic Review, Phase 1

### ISSUE THREAD

**Issue by IanMayo** [debrief/debrief#4555]
We have the first phase of Celine's review of the Debrief UI, starting with the welcome experience:
[Full-Debrief-heuristics-analysis-part-1-onboarding.pdf](https://github.com/debrief/debrief/files/3676307/Full-Debrief-heuristics-analysis-part-1-onboarding.pdf)

**Comment by helenayele** [comment]
- [ ] 5. Back button design and location
- [ ] 12.Navigation back to What’s new screen is difficult to find
- [ ] 1.Icons on Welcome screen after first start up
- [ ] 7. Inconsistent behavior between different links
- [ ] 9. Content doesn’t match First steps title
- [ ] 7. Inconsistent behavior between different links
- [ ] 11. Use of Internet Explorer is no longer supported by GitHub
- [ ]  2. Access to Welcome screen
- [ ]  3: No clear way forward for first users
- [ ]  4: Navigation menu
- [ ] #6: Content doesn’t match Overview title
- [ ] #8: Providing feedback is limited to bug and new features
- [ ] #10: Actual link content and location are not clear for users
